language: node_js
script:
  - wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
  - sudo apt-get install -y ./pandoc-2.7.3-1-amd64.deb
  - npm uninstall hexo-renderer-marked --save
  - ./node_modules/hexo/bin/hexo generate
branches:
  only:
    - source
     
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: source
notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=$DINGTALK_TOKEN