name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configuration environment
        env:
          ID_RSA: ${{secrets.id_rsa}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ID_RSA" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan dreace.top >> ~/.ssh/known_hosts
          git config --global user.name 'Dreace'
          git config --global user.email 'Dreace@Foxmail.com'
      - name: Install dependencies
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
          sudo apt-get install -y ./pandoc-2.7.3-1-amd64.deb
          npm i -g hexo-cli
          npm i hexo-deployer-git --save
          npm i hexo-wordcount --save
          npm uninstall hexo-renderer-marked --save
          npm install hexo-renderer-pandoc --save
          npm i
      - name: Deploy hexo
        run: |
          hexo g -d
